### ISSUE TITLE
Bulk loading not addressed

### ISSUE THREAD

**Issue by Downchuck** [humangeo/rawes#4]
There's no mention of bulk loading in the docs or the API. Might be something to consider. I just went ahead and built a big body request, to flush through self.es.post(data = "".join(self.body)) but _request tries to json load it.

**Comment by dwnoble** [comment]
Hi Downchuck,

I was able to successfully perform a bulk load - could your error be joining on a "" character instead of "\n" ? Also make sure to end the bulk load with an additional "\n" character (from http://www.elasticsearch.org/guide/reference/api/bulk.html): 

``` python
import rawes
import json

es = rawes.Elastic()

bulk_body = '''
{"index" : {}}
{"key":"value1"}
{"index" : {}}
{"key":"value2"}
{"index" : {}}
{"key":"value3"}
'''

es.post('aindex/atype/_bulk', data=bulk_body, params = {
    'refresh' : True
})

print "Num docs: %s" % es.aindex.atype.get('_search',params={'size':0})['hits']['total']

bulk_list = [
    {"index" : {}},
    {"key":"value4"},
    {"index" : {}},
    {"key":"value5"},
    {"index" : {}},
    {"key":"value6"}
]

# Remember to include the trailing \n character for bulk inserts
bulk_body_2 = '\n'.join(map(json.dumps, bulk_list))+'\n'

es.post('aindex/atype/_bulk', data=bulk_body_2, params = {
    'refresh' : True
})
print "Num docs: %s" % es.aindex.atype.get('_search',params={'size':0})['hits']['total']
```

I've updated the README to include this example, and added a unit test for it.

I realize this is a little annoying to manually form the body of the bulk insert via maps and json dumps.. I may try and add a helper function to do this in the near future.

Thanks for the post - if you find anything else unclear about the rawes docs please let me know!
